### ISSUE TITLE
Provide a parameter to test if connectivity with Datadog is in place

### ISSUE THREAD

**Issue by bbossola** [MeterianHQ/meterian-datadog#1]
We need a simple parameter to validate that the connecton with Datadog is in place and working ideally a simple "--validate" that prints on the console "OK" if a connection can be estabilished (and exits 0) or prints on the console "FAILURE" with possibly additional information if the connection is unsuccessful (and exits with nonzero)

**Comment by ChiedozieOkoh** [comment]
implemented in commit 52582e0f32b355a156060516950c9379e1f3838d
